### ISSUE TITLE
ytt autocomplete

### ISSUE THREAD

**Issue by DennisDenuto** [vmware-tanzu/carvel-release-scripts#3]
This issue is to track https://github.com/vmware-tanzu/homebrew-carvel/pull/20

Assuming that PR is merged, a similar change will need to be made in this repo for when ytt starts automating updating the homebrew formula

**Comment by gcheadle-vmware** [comment]
PR to add completion stuff for ytt in the automated homebrew formula update script. https://github.com/vmware-tanzu/carvel-release-scripts/pull/10
